yarnPath: .yarn/releases/yarn-4.9.2.cjs
nodeLinker: node-modules
packageExtensions:
  "@parcel/optimizer-image@2.8.1":
    dependencies:
      "@parcel/core": "^2.8.1"
  "@parcel/types@2.8.1":
    dependencies:
      "@parcel/core": "^2.8.1"
